open-component-model/delivery-service

app.py, issue_replicator/github.py, rescore.py
Fixes #
```improvement operator
```
=> Include sprint information in rescoring proposal

config.py, issue_replicator/__main__.py, issue_replicator/github.py
Useful to toggle issue-replication per finding-type without code changes.
Fixes #
```improvement operator
```
=> Introduce finding-type specific issue-replication cfg

app.py, metadata.py, middleware/decompressor.py, pylama.ini
Fixes #
```improvement operator
```
=> Add decompressor middleware

artefact_enumerator.py, compliance_summary/__init__.py, components.py, deliverydb/model.py, deliverydb/util.py, issue_replicator/__main__.py, k8s/backlog.py, metadata.py, rescore.py
Fixes #
```improvement operator
```
=> Refactor `ArtefactMetadata` model classes

compliance_summary/__init__.py, deliverydb/model.py, deliverydb/util.py, issue_replicator/github.py, metadata.py, rescore.py
Fixes #
```improvement operator
```
=> Flatten BDBA artefact metadata structure

compliance_summary/__init__.py, components.py, issue_replicator/__main__.py, metadata.py, rescore.py, rescoring_util.py, setup.utils.py, test/test_compliance_summary.py
Fixes #
```improvement operator
```
=> Don't automatically mix-in rescorings in artefact metadata query route

app.py, artefact_enumerator.py, bdba.py, compliance_tests.py, components.py, delivery_db_backup.py, dora.py, features/__init__.py, issue_replicator/__main__.py, malware/__main__.py, metadata.py, middleware/auth.py, osinfo/__init__.py, rescore.py, service_extensions.py, special_component.py, sprint.py, util.py
Fixes #
```improvement operator
```
=> Add authentication via token and enforce authenticated requests

compliance_summary/__init__.py, components.py, issue_replicator/__main__.py
Fixes #
```improvement operator
```
=> Check if scan exists based on artefact scan info

caching.py, dora.py
Fixes #
```improvement operator
```
=> Configure filesystem caching for dora instead of in-memory

compliance_summary/__init__.py, components.py, rescore.py
Fixes #
```improvement operator
```
=> Allow rescorings for findings of type `malware`

artefact_enumerator.py, issue_replicator/__main__.py, k8s/backlog.py, metadata.py, rescore.py, rescoring_util.py, service_extensions.py
Fixes #
```improvement operator
```
=> Make use of `ArtefactKind` enum

issue_replicator/__main__.py, issue_replicator/github.py
Fixes #
```improvement operator
```
=> Support issue-replication for `finding/malware`

app.py, compliance_summary/__init__.py, components.py, deliverydb/util.py, issue_replicator/github.py, metadata.py, ocm_util.py, rescore.py, rescoring_util.py, setup.utils.py
Fixes #
```improvement operator
```
=> Handle unspecified component version for findings

issue_replicator/github.py, rescore.py
Fixes #
```improvement operator
```
=> Provide and honour `scanConfigName` url param to determine scan configuration

config.py, issue_replicator/github.py, local-setup/kind/cluster/values-extensions.yaml
Fixes #
The linting errors will be resolved as soon as the corresponding change https://github.com/gardener/cc-utils/pull/1009 is published.
```improvement operator
```
=> Add configuration options for compliance milestones

metadata.py
Fixes #
```improvement user
Diki findings now reuse discovery date.
```
=> Reuse diki finding discovery date

bdba.py
https://github.com/gardener/cc-utils/pull/1031 must be merged first.
Fixes #
```improvement operator
```
=> Adjust bdba to resource group deconstruction

bdba.py, config.py
Fixes #
```improvement operator
```
=> Add cfg option to restrict finding types of BDBA scan

Dockerfile.extensions, Dockerfile.extensions.clamav, Dockerfile.service
see: https://github.com/gardener/cc-utils/pull/1036
=> switch to new image-locations

bdba/util.py
Fixes #
```improvement operator
```
=> Support local blob metadata for bdba uploads

components.py
Useful for debugging.
Also add option to bypass cache for this request.
Raw component-descriptors are never cached (for now).
Fixes #
```improvement operator
```
=> feat: Optionally get raw component-descriptor

issue_replicator/github.py
Fixes #
```improvement operator
```
=> Use direct rescoring links in compliance issue template

charts/extensions/crds/scan-configuration.yaml
Fixes #
```improvement operator
```
=> Use unified rescoring model in scan-cfg crd

app.py, bdba/__main__.py, compliance_summary/__init__.py, components.py, deliverydb/cache.py, deliverydb/util.py, metadata.py, ocm_util.py
Fixes #
```improvement operator
```
=> Add compliance summary caching

components.py, special_component.py
Fixes #
```improvement operator
```
=> Enable persistent delivery-db cache for several routes and functions

issue_replicator/github.py
Fixes #
```improvement operator
```
=> Also consider `artefact_type`, `artefact_kind` and `artefact_extra_id` for Delivery-Dashboard URL

metadata.py
Just invalidating the compliance summary with the same datatype as the metadata entry which is currently being updated is not working as desired in case the entry in question is of type `meta/artefact_scan_info`. In that case, the compliance summary for all finding types related to the datasource have to be updated, i.e. to update the summary from UNKNOWN (no scan exists) to CLEAN/FINDINGS.
Fixes #
```improvement operator
```
=> Invalidate compliance summary cache upon new artefact scan info

bdba/__main__.py, bdba/scanning.py, bdba/util.py, cli/_bdba.py
Fixes #
See commit description for more information.
```improvement operator
```
=> Consider `extraIdentity` in BDBA scans

cache_manager.py, compliance_summary/__init__.py, components.py, config.py
Fixes #
```improvement operator
```
=> Add pre-calculation of functions to cache manager

charts/delivery-service/templates/horizontal-pod-autoscaler.yaml, charts/delivery-service/templates/service-deployment.yaml
Fixes #
```improvement operator
```
=> Add horizontal pod autoscaler for delivery-service deployment

middleware/auth.py
Example role-binding cfg:
```
delivery-cfg:
auth:
oauth_cfgs:
- name: github-com
...
role_bindings:
- subjects:
- type: github-user
name: zkdev
- type: github-org
name: open-component-model
- type: github-team
name: open-component-model/ocm-gear-access
roles:
- admin
```
Fixes #
```improvement operator
```
=> Enable simple role-based authorisation

app.py, compliance_summary/__init__.py, rescore/artefacts.py
Fixes #
```improvement operator
```
=> Run expensive sync functions async in dedicated executor

features/features_cfg.yaml
Fixes #
```improvement operator
```
=> Reflect latest rescoring ruleset changes

config.py, features/__init__.py, middleware/auth.py, test/test_jwt_validation.py
Fixes #
```action operator
`DeliveryCfg` model from cc-utils will be deprecated and migration to plain `NamedModelElement` will be required.
```
=> Resolve delivery-cfg model dependency towards cc-utils

metadata.py, middleware/cors.py
Fixes #
```improvement operator
```
=> Stream and compress query metadata result

bdba/assessments.py, bdba/client.py, bdba/model.py, bdba/rescore.py, bdba/scanning.py, bdba/util.py, cli/_bdba.py
Fixes #
```improvement developer
Resolved dependency towards `model.base` in BDBA model classes
```
=> Resolve depedency towards `model.base` package

components.py, dora.py, sast.py, util.py
Fixes #
```improvement operator
```
=> move function to util

cache_manager.py, components.py, config.py, features/__init__.py, sast.py
Fixes #
```improvement operator
```
=> move versionfilter to config

backlog_controller.py, cache_manager.py, delivery_db_backup.py, malware/__main__.py, malware/clamav.py, malware/scan.py, odg/findings_cfg.yaml, odg/scan_cfg.yaml, paths.py, rescore/model.py, rescore/utility.py
Fixes #
Releases notes will be added later.
```action operator
```
=> Use overhauled scan + findings cfg for extensions

charts/extensions/charts/backlog-controller/templates/sast.yaml
Fixes #
```improvement operator
Introduce extension to verify SAST lint requirements of OCM components; Write scan results to Delivery-DB
```
=> introduce helm chart template for sast

odg/findings.py, rescore/utility.py, sast.py, test/test_rescoring.py
Fixes #
```noteworthy developer
SAST extension now uses refactored scan-cfg as well as findings-cfg
```
=> Use refactored scan-cfg and findings-cfg for sast extension

sast.py
Fixes #
```improvement operator
filter out `None` values and add loggings
```
=> Add logging and object validation

issue_replicator/__main__.py, issue_replicator/github.py
Fixes #
```noteworthy developer
Issue replicator extension now uses refactored scan-cfg as well as findings-cfg
```
=> Use refactored scan-cfg and findings-cfg for issue replicator

malware/__main__.py, odg/scan_cfg.py
Fixes #
```bugfix operator
Added filter for supported artefact types for ClamAV extension
```
=> Also filter supported artefact types for ClamAV extension

bdba/model.py, bdba/scanning.py
Fixes #
```improvement operator
```
=> Allow skipping of vulnerability findings via skip-scan label

rescore/artefacts.py, rescore/utility.py
Fixes #
```improvement operator
extend rescoring proposal to support finding type SAST
```
=> extend rescoring proposals to support SAST type

README.md
This PR updates the documentation and recommends the installation of dev packages to happen in a virtualenv.
```improvement operator
NONE
```
=> README: recommend installation of dev packages in a venv

issue_replicator/__main__.py, issue_replicator/github.py
Fixes #
```improvement operator
Extend issue template to include SAST findings and guidance.
```
=> Sast finding issue lifecycle

artefact_enumerator.py, charts/extensions/charts/sast/templates/sast.yaml, issue_replicator/__main__.py, k8s/backlog.py, odg/extensions_cfg.py, sast.py, swagger/swagger.yaml, test/test_rescoring.py
Fixes #
```improvement operator
NONE
```
=> Prevent naming conflicts by renaming sast values

sast.py
Fixes #
```improvement operator
NONE
```
=> Make SAST Logging persistent

odg/findings.py, rescore/utility.py
Fixes #
```improvement operator
introduce RescoringScope strEnum and extend Finding with default scope for better configurability
```
=> Introduce strEnum and default scope to Finding class

sast.py
Fixes #
```improvement operator
Only create Findings when skip label is not found
```
=> properly handle SAST finding creation

artefact_enumerator.py
Fixes #
```improvement user
GitHub issues are automatically updated in case a new scan exists
```
=> Trigger issue update in case a new scan exists

issue_replicator/github.py, odg/findings_cfg.yaml
Fixes #
```improvement operator
Integrated crypto extension in issue replicator
```
=> Integrate crypto extension in issue replicator

odg/crypto_defaults.yaml
Fixes #
```improvement user
Extended the list of known cryptographic libraries
```
=> Extend list of known crypto related libraries

.ci/pipeline_definitions
Fixes #
```noteworthy operator
Add qualified component assessments (via OCM labels)
```
=> Add cve-categorisation labels

issue_replicator/github.py
This PR adds more rule and ruleset information for the diki issues template. It also adds a link to the rules description.
Fixes #
```improvement operator
NONE
```
=> Improve diki rule description in diki issue template

requirements.service.txt, rescore/artefacts.py
Fixes #
```improvement user
BLIs are now created upon rescorings based on the configured grouping attributes for the issue replicator
```
=> Adjust BLI creation upon rescorings to configurable grouping

consts.py, deliverydb/__init__.py, deliverydb/cache.py, middleware/db_session.py
Fixes #
```improvement developer
Grouped non-urgent DB updates in a dedicated (smaller) session
```
=> Group non-urgent DB updates in a dedicated (smaller) session

compliance_summary/__init__.py, compliance_summary/artefact_metadata_cfg.yaml, deliverydb/model.py, odg/findings.py, odg/findings_cfg.yaml, odg/profiles.yaml, swagger/swagger.yaml
Fixes #
```noteworthy user
Dropped support for deprecated Checkmarx findings
```
=> Remove checkmarx leftovers

cache_manager.py, delivery_db_backup.py
Fixes #
```improvement operator
```
=> Adjust extensions to delivery-db secret model changes

compliance_summary/__init__.py
Fixes #
```improvement user
Optimised the calculation (time) for the compliance summary
```
=> Optimise compliance summary calculation

k8s/util.py
Fixes #
```improvement operator
```
=> Add more flexibility to k8s-client factory

.ci/build_python_packages, .github/workflows/build.yaml, .github/workflows/non-release.yaml, .github/workflows/release.yaml
```improvement developer
switch build and release-pipelines for odg to github-actions
```
=> Switch to gha

artefact_enumerator.py, cache_manager.py, charts/extensions/Chart.yaml, charts/extensions/charts/os-id/Chart.yaml, charts/extensions/charts/os-id/templates/os-id.yaml, charts/extensions/values.yaml, compliance_summary/__init__.py, eol.py, odg/extensions_cfg.py, odg/findings.py, odg/profiles.yaml, os_id_extension/__main__.py, os_id_extension/scan.py, os_id_extension/util.py, osinfo/__init__.py, osinfo/alpine.py, osinfo/model.py, rescore/artefacts.py, rescore/utility.py, setup.extensions.py, setup.service.py, setup.utils.py, test/test_compliance_summary.py
Fixes #
```improvement operator
Add OSID Extension
```
=> Os ids extension

.github/workflows/build.yaml, .ocm/component-references.yaml
Fixes #
```improvement operator
NONE
```
=> declare ocm dependency towards cc-utils

charts/extensions/charts/os-id/templates/os-id.yaml
Fixes #
```improvement operator
NONE
```
=> use correct service name osId instead of os-id

osid_extension/__main__.py
removes `is_one_patch_behind` method, which attempted to parse version strings using semver and failed for simple versions like `12`. instead, we now rely on  the existing update_available logic, which already handles patch-level comparisons
Fixes #
```improvement operator
NONE
```
=> rm check and use existing method instead

issue_replicator/github.py
Fixes #
```improvement operator
Integrate osid extension in issue replicator
```
=> integrate osid extension in issue replicator

.github/workflows/build.yaml, .github/workflows/non-release.yaml, .github/workflows/release.yaml
Fixes #
```improvement operator
refactor github-actions-pipelines (reuse reusable workflows from cc-utils)
```
=> Refactor gha

.github/workflows/build.yaml, .github/workflows/non-release.yaml, .github/workflows/release.yaml
Fixes #
```improvement developer
cleanup: drop (now) unnecessary inputs/outputs
```
=> cleanup: drop (now) unnecessary inputs/outputs

osid_extension/__main__.py
Fixes #
```improvement operator
Handle distroless Images
```
=> handle distroless image status

metadata.py
Fixes #
```improvement operator
NONE
```
=> extend method of reusing descovery date with os id

issue_replicator/github.py
Fixes #
```improvement operator
NONE
```
=> Fix line too long linter

osid_extension/__main__.py
ensures that osid findings are only created for external artefacts if the corresponding os branch has reached end-of-life 
Fixes #
```improvement operator
osid findings are no longer created for external artefacts unless the underlying os branch is EOL.
```
=> Only create osid findings for external resources if branch is EOL

osid_extension/__main__.py
Fixes #
```improvement operator
OSID extension now honours artefact filters + supported artefact kinds
```
=> Also honour artefact filter and supported kinds in osid extension

issue_replicator/github.py, odg/findings.py, odg/findings_cfg.yaml
This PR adds support for `finding/inventory` type.
Fixes #
```improvement operator
Add support for inventory/finding type
```
=> feat: add support for `finding/inventory`

issue_replicator/github.py
Preserve the already passed summary and append to it.
Fixes #
```improvement operator
None
```
=> issue_replicator: do not overwrite summary for Inventory findings

.github/workflows/build.yaml, artefact_enumerator.py, charts/extensions/Chart.yaml, charts/extensions/charts/responsibles/Chart.yaml, charts/extensions/charts/responsibles/templates/responsibles.yaml, charts/extensions/values.yaml, issue_replicator/__main__.py, issue_replicator/github.py, local-setup/kind/cluster/values-bootstrapping.yaml, local-setup/kind/cluster/values-extensions.yaml, local-setup/local-setup.md, metadata.py, odg/extensions_cfg.py, odg/extensions_cfg.yaml, odg/findings.py, odg/model.py, responsibles_extension/__main__.py, responsibles_extension/filters.py, responsibles_extension/strategies.py, setup.extensions.py, swagger/swagger.yaml
Fixes #
```noteworthy operator
Added a new extension `responsibles` which allows fine-granular configuration for responsible strategies
```
```improvement developer
Added option `assignee_mode` to control behaviour in case GitHub issue already has different assignees
```
=> Add `responsibles` extension

artefact_enumerator.py, backlog_controller.py, bdba_extension/__main__.py, cache_manager.py, crypto_extension/__main__.py, delivery_db_backup.py, issue_replicator/__main__.py, malware/__main__.py, odg/extensions_cfg.py, odg/util.py, osid_extension/__main__.py, responsibles_extension/__main__.py, sast.py
Fixes #
```improvement developer
Common extension "framework" is now factored-out into dedicated `odg.util` module
```
=> Factor-out common extension "framework" into dedicated `odg.util` module

.github/workflows/publish_bdba_client.yaml, .github/workflows/publish_development_kit.yaml
Fixes #
```improvement operator
```
=> Add workflow to manually trigger PyPI upload of BDBA client package

odg/util.py
This option allows the `process_backlog_items` function to be operated in a "local-mode", in case a `local_debug_artefact` is passed. This will shortcut any interactions with a Kubernetes cluster and will use the passed-in artefact as dummy backlog item instead. This is useful for local development scenarios.
Fixes #
```improvement developer
Allows "local-mode" of backlog item processing for local setup of an extension
```
=> Allow "local-mode" for backlog item processing of extensions

issue_replicator/github.py
As diki creates database entries with same data-key but different component version, we have remember already created issues. Otherwise all findings are processed individually and for each finding a new issue could be created (even though there is one for this data-key already).
Fixes #
```improvement developer
For issue-per-finding case (diki), newly created issues are now also considered when looking up for known/existing issues.
```
=> fix: Prevent duplicate diki issues

odg/model.py, rescore/artefacts.py, rescore/utility.py
Fixes #
```improvement developer
Rescoring proposal are now more consistent and require less finding-type specific logic
```
=> Make rescoring proposals more consistent and require less finding-type specific logic

.github/workflows/upgrade-dependencies.yaml
Fixes #
```improvement developer
add create upgrade-pullrequest-workflow (for GitHub-Actions pipeline)
```
=> add create upgrade-pullrequest-workflow

charts/extensions/Chart.yaml, charts/extensions/charts/odg-operator/Chart.yaml, charts/extensions/charts/odg-operator/templates/deployment.yaml, charts/extensions/charts/odg-operator/templates/extension-definitions.yaml, charts/extensions/charts/odg-operator/templates/rbac.yaml, charts/extensions/crds/odg.yaml, charts/extensions/values.yaml
Fixes #
```improvement operator
NONE
```
=> Add odg-operator deployment

odg_operator/__main__.py
Fixes #
```improvement operator
```
=> ODG: clean up extensions on modification

ocm_util.py
Fixes #
```improvement operator
```
=> Fix: Use `netloc` to convert relative to absolute OCI access

issue_replicator/github.py
This caused newly created issues to be directly closed afterwards.
Fixes #
```improvement user
Fix: Newly created GitHub issues (per finding) are not closed anymore directly after creation
```
=> fix: Add newly created GitHub issues to list of processed issues

bdba_extension/scanning.py
Fixes #
```improvement operator
Package-Version-Hint labels on component level are now also honoured as a fallback
```
=> Use package-version-hint label of component as fallback

artefact_enumerator.py
Fixes #
```improvement operator
fix: Always honour `enabled` flag of issue-replicator extension
```
=> fix: Always honour `enabled` flag of issue-replicator extension

charts/bootstrapping/templates/secrets.yaml, charts/delivery-service/templates/service-deployment.yaml
Fixes #
```improvement operator
Honour `rbac` configuration in Helm charts as well
```
=> Honour `rbac` configuration in Helm charts as well

extension-definitions.yaml
Fixes #
```noteworthy operator
The target namespace is included in the Ingress Class name for the Delivery-Service
```
=> Explicitly overwrite Ingress Class name (include target namespace)

docs/local_setup.rst
Fixes #
```improvement operator
```
=> Update docu for Local Development Setup

artefact_enumerator.py, bdba/client.py, odg/extensions_cfg.py, secret_mgmt/__init__.py, secret_mgmt/blackduck.py
needed for BlackDuck integration
Fixes #
```improvement operator
```
=> Extend extension cfg, artefact enumerator and secretmgmt

issue_replicator/__main__.py, issue_replicator/github.py, odg/model.py
Fixes #
```improvement user
GitHub issues now contain references of historical findings and/or previous issues
```
```noteworthy operator
GitHub issue template is now more unified and supports a fallback case for unknown finding types
```
```action operator
Diki and Kyverno findings now only support the `summary` template variable (instead of `title`, `text`, `info` and `events`)
```
=> Improve GitHub issue replication
