- artefact_enumerator.py
- deliverydb/util.py
- k8s/backlog.py
- metadata.py
- rescore.py
- remove special "context handling" which was required for upload of bdba scan results
- mimic normal http PUT semantic (arbitrary number of the same request will result in exactly one item stored in the db)
- removal of stale metadata has to be implemented by each client
Fixes #
```improvement operator
```
> Overhaul update metadata route

- malware/__main__.py
- malware/clamav.py
- malware/scan.py
Required for finding specific tracking (and rescoring). Use artefact-metadata type `meta/artefact_scan_info` to store which artefacts have been scanned. Previously, this was realised with aggregated malware findings with empty result lists.
Fixes #
```improvement operator
```
> Store malware findings individually

- app.py
They have been renamed to `ocm` instead.
Fixes #
```improvement operator
```
> Remove deprecated `cnudie` routes

- app.py
- artefact_enumerator.py
- bdba.py
- issue_replicator/__main__.py
- issue_replicator/github.py
- k8s/backlog.py
- k8s/model.py
- k8s/runtime_artefacts.py
- k8s/util.py
- malware/__main__.py
- service_extensions.py
This change introduces the handling for a new Kubernetes custom resource definition (CRD) `RuntimeArtefact`. Its purpose is to represent those artefacts, which are not part of OCM but still need to be processed in several extensions of the OCM-Gear, such as the artefact enumerator or the issue replicator. Just as component descriptors are created and uploaded independently of the OCM-Gear, those runtime artefacts should also be created/updated/deleted by external tooling which has knowledge of existing runtime artefacts. Therefore, this change also adds new API routes supporting this request. As soon and as long a CR for a runtime artefact exists, it will be part of the extension machinery just as traditional OCM resources and sources, except they …
> Add runtime artefacts as CRD to extension workflows

- issue_replicator/__main__.py
- issue_replicator/github.py
This also fixes a bug where the "scan-pending" semantic did not work properly in case multiple versions of the same artefact are in the scanned BoM, while some of the versions were scanned and others were not. With this change, an issue gets the "scan-pending" label if at least one of the contained artefact versions is not scanned yet (thus keeping the issue open although no finding might be found yet). Before, only issues were all contained artefact versions had no scan were labeled and considered as "scan-pending".
Fixes #
```improvement operator
```
> Display artefact versions without scan in GitHub issue

- config.py
- issue_replicator/__main__.py
- issue_replicator/github.py
- local-setup/kind/cluster/values-delivery-gear-extensions.yaml
This PR improves the Issue Replicator by allowing it to create multiple issues for an artefact per found findings for it by setting the `enable_issue_per_finding` field of `finding_type_issue_replication_configs` to `true`.
There are a few minor changes to the old flow of issues creation, the iteration of issues is done in a later state and now when there are 2 or more open issues with the specific label a warning is logged as suppose to an Error.
The new flow of creating issues per finding differs by iterating all findings and executing `_create_or_update_issue` per finding, it also deletes all know issues that had not been updates or created.
This PR also adapts Issues Replicator to be able to process findings of type `finding/diki`.
**Which …
> Adapt Issue Replicator to process diki findings

- issue_replicator/github.py
This PR improves `_diki_template_vars()` function to handle merged diki findings. These findings are from compliance checks on more than 1 evaluated instance.
It also places a hard limit of `60,000` character to the full returned summary. When this limit is exceeded the returned summary is in a shortened format. This is done to avoid reaching GitHub's character limit of `65,536` for Issues, PRs, comments, etc.
Fixes #
```improvement operator
NONE
```
> Modify `_diki_template_vars()` to handle merged findings

- bdba/__main__.py
- bdba/scanning.py
- cli/_bdba.py
- ocm_util.py
Useful to support various artefact types.
Can be used as a callback for code which should not bother with resolving ocm artefacts.
Fixes #
```improvement operator
```
> Add content-iterator to BDBA scans

- app.py
- components.py
This PR extends the greatest_component_versions route in the delivery-service to support filtering by a specified date range. Users can now provide optional start_date and end_date parameters to retrieve component versions within a specific timeframe. 
Fixes #
This PR is dependent on another [PR](https://github.com/gardener/cc-utils/pull/1050). Please ensure both are reviewed together to maintain compatibility.
```improvement operator
```
> Extend greatest_component_versions to support filtering by date range

- app.py
- local-setup/kind/cluster/values-prometheus.yaml
- local-setup/kind/kind-up.sh
- local-setup/kind/kind-update.sh
- middleware/prometheus.py
- requirements.service.txt
- adds external `prometheus` resource to component descriptor
- enables optional `prometheus` feature by passing `--prometheus` argument
- if the feature is enabled, it will expose an additional `/metrics` endpoint which can be scraped by Prometheus
- Prometheus endpoint will be available under `<delivery-service-url>/prometheus`
- by now, 3 metrics are going to be monitored:
-> `request_latency_seconds`
-> `requests_in_progress_total`
-> `requests_total`
Fixes #
```improvement operator
```
> Expose prometheus metrics to `/metrics` endpoint

- bdba/__main__.py
- bdba/rescore.py
- bdba/scanning.py
- config.py
Avoid duplication of rescoring rule sets across delivery-service and extension configs.
Fixes #
```improvement operator
```
> Unify rescoring rule sets

- issue_replicator/github.py
Fixes #
```improvement operator
```
> fix: Properly filter for overdue findings when jumping to delivery-dashboard

- bdba/util.py
- components.py
- delivery_db_backup.py
- rename: cnudie.upload -> ocm.upload
- inline gci.oci's "to-digest"-code
ref: https://github.com/gardener/cc-utils/pull/1081
> adjust to upstream refactoring (cc-utils)

- .ci/pipeline_definitions
- Dockerfile.extensions.cache-manager
- cache_manager.py
- charts/extensions/charts/cache-manager/Chart.yaml
- charts/extensions/charts/cache-manager/templates/cache-manager.yaml
- charts/extensions/values.yaml
- config.py
- setup.service.py
Fixes #
```improvement operator
```
> Add cache manager extension

- bdba/__main__.py
- cli/_bdba.py
- ocm_util.py
local blob size is optional
Fixes #
```improvement operator
```
> Fallback to lookup blob size in oci-manifest

- bdba/scanning.py
- bdba/util.py
- config.py
Reduce dependencies from delivery-service-repository towards cc-utils (in particular such dependenceis against cc-util's pipeline-template).
As GithubIssueTemplateCfg is quite a trivial datastructure, copy it for now (will be deduplicated again by planned mv of upstream github.compliance-package - which is currently blocked by remaining, pipeline-based scans (CX + OS-id), yet to be migrated into ocm-gear-extensions).
LicenseCfg was not longer used within cc-utils.
> refactor: import dataclasses from cc-utils / pipeline-template

- artefact_enumerator.py
- bdba/__main__.py
- delivery_db_backup.py
- issue_replicator/__main__.py
- lookups.py
- malware/__main__.py
Adjust to upstream refactoring from:
https://github.com/gardener/cc-utils/pull/1102
```improvement developer
Slightly reduce dependencies towards Gardener-CICD. Pass-in auth-token-lookup thus making delivery-service-client no longer (directly) depend on "CfgFactory".
```
> pass token-lookups to deliveryservice-client

- issue_replicator/__main__.py
- issue_replicator/github.py
Compliance snapshots are only being created for sprints of a configured date interval. However, as of before this change, the issue replicator considered all sprints returned by the delivery-service api and grouped the open findings among these sprints. As not all of these sprints must have a respective compliance snapshots (i.e. if the sprint is not part of the configured date interval), the finding is not being reported in the GitHub issues.
To fix this, this change only considers the sprints determined from the compliance snapshots and groups the findings among these sprints. That way, the configured interval for the artefact enumerator is the single sourth of truth and all findings are being reported only for these sprints.
**Which issue(s) this …
> Only use sprints from compliance snapshots for issue replication

- .ci/pipeline_definitions
- charts/bootstrapping/Chart.yaml
- charts/bootstrapping/templates/helpers.tpl
- charts/bootstrapping/templates/secrets.yaml
- charts/delivery-service/templates/service-deployment.yaml
- charts/extensions/charts/artefact-enumerator/templates/artefact-enumerator.yaml
- charts/extensions/charts/backlog-controller/templates/backlog-controller.yaml
- charts/extensions/charts/backlog-controller/templates/bdba.yaml
- charts/extensions/charts/backlog-controller/templates/clamav.yaml
- charts/extensions/charts/backlog-controller/templates/issue-replicator.yaml
- charts/extensions/charts/cache-manager/templates/cache-manager.yaml
- charts/extensions/charts/delivery-db-backup/templates/delivery-db-backup.yaml
Fixes #
```noteworthy operator
Added `bootstrapping` chart which allows installation of required secrets
```
```noteworthy operator
Added (for-now-)optional volume mounts for secrets installed by `bootstrapping` chart (replaces `cfg-factory-secret`)
```
> Add `bootstrapping` helm-chart and volume mounts for dedicated secrets

- issue_replicator/github.py
Fixes #
```improvement operator
NONE
```
> Remove misleading `0 targets` in diki issues template

- app.py
- cm06/scan.py
- config.py
- features/__init__.py
- rescore/model.py
- rescore/utility.py
- test/test_rescoring.py
Fixes #
```improvement operator
```
> Sast rescoring update

- odg/defaults.yaml
- odg/findings.py
- odg/scan_cfg.py
- setup.utils.py
As a first step, these model classes are kept totally redundant to the current ones defined in `config.py` to allow a step-by-step transition towards the overhauled cfg-mgmt. This will allow existing extensions and in the end the delivery-service + -dashboard themselves to switch to the overhauled cfg-mgmt one by one as long as the provided configuration is kept semantically equal.
Fixes #
```noteworthy developer
Add new `odg` package containing overhauled and new model classes
```
> Add refactored scan cfg and new finding-specific model classes

- bdba/__main__.py
- bdba/assessments.py
- bdba/scanning.py
- bdba/util.py
- charts/extensions/crds/scan-configuration.yaml
- cli/_bdba.py
- config.py
- local-setup/kind/cluster/values-extensions.yaml
As of now, BDBA triages are stored as rescorings in the delivery-db using the `SINGLE` scope, i.e. they are not re-used across new artefact versions. With this change, the scope is extended to `ARTEFACT`, so they will be also applied to new versions, however, not among different artefact extra ids (this is different to now!).
With that, we no longer have to also re-apply existing BDBA triages to new BDBA apps, as we use the rescorings in the delivery-db as single sourth of truth anyways (the BDBA UI may show findings already which actually don't have to be assessed anymore because they were already assessed using the delivery-dashboard).
This also elimnates the requirement to delete old BDBA apps, as it was required as an optimisation to have less …
> Stop re-applying existing BDBA triages to new BDBA apps

- odg/scan_cfg.py
- test/test_extension_cfg.py
Allows explicit control whether an extension should be enabled. Previously, this was handled implicitly by absence of configuration.
This is useful for two reasons:
- allows operator to toggle extension state with minimal effort (plus one can keep "old" configuration)
- is more intuitive in case an extension does not provide configuration (e.g. because defaults are sufficient, like in SAST case)
This change is backwards compatible and defaults to `True`.
Fixes #
```improvement operator
ODG extension state can now be explicitly toggled via `enabled` flag (backwards compatible)
```
> Introduce `enabled` flag to extension cfgs

- issue_replicator/__main__.py
- odg/extensions_cfg.py
The artefact enumerator is configured with a time range for which it creates respective compliance snapshots. As these compliance snapshots (or more precisely: their correlation id), is used as a reference to the GitHub issues, only issues which have a correlation id for which a compliance snapshot exists are being considered for the automatic issue lifecycle. Now, if a compliance snapshot becomes inactive and no new snapshot is created with the same correlation id (because by now the due date is not part of the configured interval anymore), the respective GitHub issue is not considered anymore by the automatic issue lifecycle.
To mitigate this, this fix will consider all sprints (for active and inactive snapshots), but will only assign findings to …
> Fix: Close issues which "fell out" of the configured time range

- artefact_enumerator.py
- issue_replicator/__main__.py
- issue_replicator/github.py
- k8s/backlog.py
- odg/findings.py
Fixes #
Example configuration which matches the status-quo:
```yaml
type: finding/vulnerability
issues:
enable_issues: True
attrs_to_group_by:
- component_name
- artefact_kind
- artefact.artefact_name
- artefact.artefact_type
```
```improvement operator
Added optional grouping configuration to configure grouping rules for GitHub issue replication
```
> Allow custom GitHub issue grouping in finding-cfg 

- charts/bootstrapping/templates/extensions-cfg.yaml
- charts/bootstrapping/templates/features-cfg.yaml
- charts/bootstrapping/templates/findings.yaml
- charts/bootstrapping/templates/ocm-repo-mappings.yaml
- charts/bootstrapping/templates/profiles.yaml
- charts/bootstrapping/templates/secrets.yaml
- charts/delivery-service/templates/horizontal-pod-autoscaler.yaml
- charts/delivery-service/templates/rbac.yaml
- charts/delivery-service/templates/service-deployment.yaml
- charts/delivery-service/templates/service-ingress.yaml
- charts/delivery-service/templates/service-service.yaml
- charts/extensions/charts/artefact-enumerator/templates/artefact-enumerator.yaml
- charts/extensions/charts/backlog-controller/templates/backlog-controller.yaml
- charts/extensions/charts/bdba/templates/bdba.yaml
- charts/extensions/charts/cache-manager/templates/cache-manager.yaml
- charts/extensions/charts/clamav/templates/clamav.yaml
- charts/extensions/charts/clamav/templates/freshclam-config.yaml
- charts/extensions/charts/clamav/templates/freshclam-service.yaml
- charts/extensions/charts/clamav/templates/freshclam.yaml
- charts/extensions/charts/crypto/templates/crypto.yaml
- charts/extensions/charts/delivery-db-backup/templates/delivery-db-backup.yaml
- charts/extensions/charts/issue-replicator/templates/issue-replicator.yaml
- charts/extensions/charts/sast/templates/sast.yaml
Useful for scenarios where helm release namespace cannot be controlled, e.g. when deploying using gardener-resource-manager.
Fixes #
```improvement operator
Add target namespace overwrite via values (not built-in helm objects only)
```
> Add target namespace overwrite via values (not built-in helm objects only)

- backlog_controller.py
- charts/extensions/charts/bdba/templates/bdba.yaml
- charts/extensions/charts/clamav/templates/clamav.yaml
- charts/extensions/charts/crypto/templates/crypto.yaml
- charts/extensions/charts/issue-replicator/templates/issue-replicator.yaml
- charts/extensions/charts/sast/templates/sast.yaml
- k8s/util.py
There are several reasons:
- consistency with our other helmcharts
- established best practise in k8s community
- technical benefits, e.g. controlled rollout of new image versions
- gardener-resource-manager does not support "preserve-replicas" for
replica-sets
Fixes #
```action operator
ODG extension replica-sets are wrapped via `Deployment` 
```
> Wrap replica-sets in deployments

- middleware/db_session.py
A DB connection timeout error is raised in case the session pool is full, i.e. the pool size of "5" and the possible overflow of "10" is exceeded. In that case, raise a http 503 error so that the load balancer (ingress nginx controller) is able to forward the request to the next available pod which might have a session pool capacity left.
Fixes #
```noteworthy developer
A http `503 service unavailable` error is now raised in case a DB connection timeout occurs
```
> Raise `503 service unavailable` error upon DB connection timeout

- features/__init__.py
- local-setup/kind/cluster/values-bootstrapping.yaml
- secret_mgmt/__init__.py
- secret_mgmt/delivery_db.py
Different database technologies are still supported (e.g. sqlite for local dev), however only if db-url is passed directly via args.
When using central configuration approach (e.g. via mODG), assume database is of type postgres.
Also, remove redundant definition of cluster internal access aspects, such as runtime namespace.
Fixes #
```action operator
Only support postgres as delivery-db database technology for mODG instances
```
```improvement operator
Drop redundant cluster-specific namespace definition
```
> Only support postgres for managed ODG installations

- artefact_enumerator.py
- bdba_extension/util.py
- crypto_extension/__main__.py
- deliverydb/model.py
- deliverydb/util.py
- issue_replicator/__main__.py
- issue_replicator/github.py
- malware/__main__.py
- odg/findings.py
- osid_extension/__main__.py
- rescore/artefacts.py
- rescore/utility.py
- sast.py
Fixes #
```improvement developer
`due_date` (fka. `latest_processing_date`) is now stored as part of findings + rescorings
```
```noteworthy user
categorisations which require a user input for `due_date` are now supported
```
> Store `due_date` for findings + rescorings and allow manual processing-time inputs

- issue_replicator/github.py
Fixes #
```improvement operator
NONE
```
> Improve diki template vars

- issue_replicator/github.py
- odg/findings.py
For now, use still the raw data key in case it does not exceed GitHub's limitations to ensure backwards compatibility. Once all existing GitHub issues also have the digest-based label attached, this code path can be removed again.
Fixes #
```improvement developer
Use digest-based data-key as GitHub label instead of raw data-key
```
> Use digest-based data-key as GitHub label to adhere to GitHub limits

- artefact_enumerator.py
- issue_replicator/__main__.py
- local-setup/kind/cluster/values-bootstrapping.yaml
- odg/extensions_cfg.py
- odg/model.py
- rescore/artefacts.py
Some time ago, each compliance snapshot directly correlated to a specific GitHub issue by containing the `issue_id`, fka. `correlation_id`. Since this `issue_id` also contains the `due_date`, there were one compliance snapshot for each sprint for each artefact.
Ever since the `issue_id` is not stored anymore directly in the compliance snapshots, but calculated ad-hoc by the issue-replicator using the provided configuration, the only purpose of the compliance snapshots is to store the states of the individual extensions (e.g. when they were executed the last time).
Since this information was stored redundantly among all compliance snapshots of an artefact anyways, it is now possible to store only _one_ compliance snapshot per artefact containing all …
> Only ever create one compliance snapshot per artefact

- charts/delivery-service/templates/service-ingress.yaml
- local-setup/kind/cluster/values-delivery-service.yaml
We removed ingress controller flexibility as a preparation for a managed offering. While we still want to offer a lightweight out-of-the-box expierence, it is required to support more sophisticated use-cases which consume the helm charts directly.
Fixes #
```noteworthy operator
Ingress controller class name of delivery-service can now be overwritten
```
> Do not hardcode nginx ingress

- ocm_util.py
- odg_operator/odg_controller.py
- odg_operator/odg_model.py
- odg_operator/odg_util.py
- rescore/artefacts.py
- test/resources/extension-definitions.yaml
- test/test_modg_extension.py
- util.py
Reconciles ODG resources in mODG-root cluster and creates ODG-Extension resources (via gardener-resource-manager).
Fixes #
```improvement operator
```
> Add ODG controller

- charts/delivery-service/templates/default-deny.yaml
- charts/delivery-service/templates/service-deployment.yaml
- charts/extensions/charts/artefact-enumerator/templates/artefact-enumerator.yaml
- charts/extensions/charts/backlog-controller/templates/backlog-controller.yaml
- charts/extensions/charts/bdba/templates/bdba.yaml
- charts/extensions/charts/cache-manager/templates/cache-manager.yaml
- charts/extensions/charts/clamav/templates/clamav.yaml
- charts/extensions/charts/clamav/templates/freshclam.yaml
- charts/extensions/charts/crypto/templates/crypto.yaml
- charts/extensions/charts/delivery-db-backup/templates/delivery-db-backup.yaml
- charts/extensions/charts/issue-replicator/templates/issue-replicator.yaml
- charts/extensions/charts/osid/templates/osid.yaml
- charts/extensions/charts/responsibles/templates/responsibles.yaml
- charts/extensions/charts/sast/templates/sast.yaml
Deny all egress and ingress traffic by default.
Explicitly all traffic for certain pods.
Fixes #
```action developer
Added network policies which deny all traffic by default. For all ODG pods requiring egress or ingress, corresponding network policy rules have been defined.
```
> Define network policies

- Dockerfile.extensions.clamav
alpine edge contains an outdated version of `libcrypto3` (`3.3.2-r4`, whereas `3.5.0-r0` is latest available).
`clamav 1.4.3` is not compatible with the older version of `libcrypto3` anymore.
Fixes #
```improvement operator
Ensure "libcrypto3" package is compatible to "clamav" malware scanner
```
> fix: Ensure `libcrypto3` is compatible with `clamav`

- charts/extensions/charts/clamav/templates/clamav.yaml
- charts/extensions/values.yaml
Will be required for mODG, as deployment annotations are used by gardener-resource-manager to prevent rollback of scaling.
see:
https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#preserving-replicas-or-resources-in-workload-resources
Fixes #
```noteworthy operator
Support optional deployment annotations for ClamAV
```
> Allow optional clamav deployment annotations

- .github/workflows/build.yaml
- Dockerfile.extensions
- requirements.extensions.txt
- setup.extensions.py
Fixes #
```improvement operator
odg-operator (and dependencies) is now part of extensions oci-image
```
> Add odg-operator (and dependencies) to extensions oci-image

- charts/extensions/charts/odg-operator/templates/deployment.yaml
Necessary to consume extension-cfg in odg-operator.
Fixes #
```noteworthy operator
Extension-cfg is now mounted to odg-operator.
```
> feat(odg): Mount extension-cfg to odg-operator

- odg/extensions_cfg.py
- odg/extensions_cfg.yaml
- odg_operator/__main__.py
Additionally reading odg-extension-definition references from the extension-cfg is useful, as we enable a more convienent way to configure the operator.
This is especially useful considering we deploy via a helm-values pre-processing step (generate_helm_values.py).
Fixes #
```noteworthy operator
odg-extension-definitions can now also be passed via extension-cfg.
```
> feat(modg): Add more options to pass extension-definitions

- extension-definitions.yaml
Fixes #
\cc @8R0WNI3 
both extensions are implemented as k8s cronjob.
This requires certain configuration to be rendered into the manifest.
Therefore, this cannot be installed by odg users via runtime configuration.
Do **not** expose these config options via odg-operator interface for now, but rely on sane defaults specified in helm charts.
```improvement operator
delivery-db odg-extension is now also available via managed open-delivery-gear
```
> feat(modg): Add missing ODG extension-definitions

- charts/bootstrapping/templates/secrets.yaml
postgres requires a password which must either be templated into the deployment itself, or be referenced via a secret.
first variant is no option, because the manifest is templated centrally (odg-operator) and has no user secrets at hand. thus, deploy a secret in user cluster (as part of bootstrap chart) which the postgres deployment can use to extract the password.
Fixes #
```improvement operator
```
> feat(modg): Deploy delivery-db password as secret

- charts/delivery-service/templates/default-deny.yaml
Allows disabling the deployment of a "default-deny" network policy which denies all ingress and egress traffic by default in the target namespace.
Fixes #
```improvement operator
Added `disableDefaultDenyPolicy` Helm value to delivery-service chart
```
> Add `disableDefaultDenyPolicy` to delivery-service Helm chart

- ocm_util.py
- rescore/artefacts.py
Fixes #
```improvement developer
The rescoring route is now capable of handling artefacts with empty string values instead of empty values
```
> Allow `ComponentArtefactId` to contain empty strings instead of `None`
